baseURL = 'https://RRInfo.net/'
locale = 'en-us'
title = 'RRInfo.net'

[params.taxonomy]
    taxonomyCloud = ['tags', 'manufacturers']

    taxonomyCloudTitle = ['Tags', 'Manufacturers']

    taxonomyPageHeader = ['tags', 'manufacturers']

[params.ui]
    showLightDarkModeMenu = true
    navbar_logo = false
    sidebar_menu_foldable = true

[taxonomies]
    tag = "tags"
    manufacturer = "manufacturers"

[permalinks]
    manufacturers = '/modeling/manufacturers/:title'

[module]
    proxy = "direct"
    [module.hugoVersion]
        extended = true
        min = "0.160.1"
    [[module.imports]]
        path = "github.com/google/docsy/theme"
        disable = false